# -*- coding: utf-8 -*-
"""#ArtManagement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdUUTCZ5xEPRUbTAXDRa0lLOzO2Sk2PB
"""

#NOTE: i used pycharm to do the code but this is the eassiest and most reliablie way for me to share the file :)


#Art management
import random


class Artwork:
    def __init__(self, title, artist, date_of_creation, historical_significance, location, is_special=False):
        self.title = title
        self.artist = artist
        self.date_of_creation = date_of_creation
        self.historical_significance = historical_significance
        self.location = location
        self.is_special = is_special


class Exhibition:
    def __init__(self, title, duration, location, artworks):
        self.title = title
        self.duration = duration
        self.location = location
        self.artworks = artworks


def generate_random_artwork():
    titles = ["Mona Lisa", "Starry Night", "The Persistence of Memory", "The Last Supper", "Guernica",
              "The Creation of Adam", "The Scream", "Girl with a Pearl Earring"]
    artists = ["Leonardo da Vinci", "Vincent van Gogh", "Salvador Dalí", "Leonardo da Vinci", "Pablo Picasso",
               "Michelangelo", "Edvard Munch", "Johannes Vermeer"]
    dates = ["1503–1506", "1889", "1931", "1495–1498", "1937", "1508–1512", "1893", "1665"]
    significance = ["One of the most famous paintings in the world", "Known for its swirling clouds and bright stars",
                    "Depicts melting clocks in a dreamlike landscape",
                    "One of the most recognizable religious paintings", "A powerful anti-war painting",
                    "Fresco painting on the ceiling of the Sistine Chapel", "Symbolist painting representing anxiety",
                    "Famous for its pearl earring worn by the subject"]
    locations = ["Permanent Gallery", "Permanent Gallery", "Permanent Gallery", "Permanent Gallery",
                 "Permanent Gallery", "Permanent Gallery", "Permanent Gallery", "Permanent Gallery"]
    is_special = [False, False, True, False, True, False, False,
                  False]  # Indicates whether the artwork is part of a special event

    idx = random.randint(0, len(titles) - 1)
    title = titles[idx]
    artist = artists[idx]
    date = dates[idx]
    significance = significance[idx]
    location = locations[idx]
    special = is_special[idx]

    return Artwork(title, artist, date, significance, location, special)


def display_artworks(artworks):
    print("Artwork Catalog:")
    for idx, artwork in enumerate(artworks, start=1):
        print(f"Artwork {idx}:")
        print(f"Title: {artwork.title}")
        print(f"Artist: {artwork.artist}")
        print(f"Date of Creation: {artwork.date_of_creation}")
        print(f"Historical Significance: {artwork.historical_significance}")
        print(f"Location: {artwork.location}")
        print(f"Special: {'Yes' if artwork.is_special else 'No'}")
        print()


# Create artworks and exhibitions
artworks = [generate_random_artwork() for _ in range(8)]
exhibition = Exhibition("Masterpieces of Art", "3 months", "Exhibition Hall", artworks)

# Display the catalog of artworks
display_artworks(artworks)

